<?php
    include_once('templates/tlp_common.php');
    include_once('templates/tlp_account.php');
    //session_start();
    draw_header();
    draw_navbar();
    draw_login();
    //print($_SESSION['username']);
    //draw_footer();
?>